/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.utfpr.alvaras.gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.net.URL;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;
import net.lib.easyconfig.EasyConfig;
import org.utfpr.alvaras.control.Choreographer;
import org.utfpr.alvaras.control.ResponsibilityChain;
import org.utfpr.alvaras.control.impl.BingGeocoding;
import org.utfpr.alvaras.control.impl.ClassifyChainLink;
import org.utfpr.alvaras.control.impl.GISExporter;
import org.utfpr.alvaras.control.impl.GeocodingChainLink;
import org.utfpr.alvaras.leitor.LerCSV;
import org.utfpr.alvaras.model.Alvara;

/**
 *
 * @author henrique
 */
public class MainFrame extends javax.swing.JFrame {

    private Properties config;
    private MainFrame thisFrame;
    private Thread execution = null;
    private boolean stopExecution = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        thisFrame = this;

        Properties model = new Properties();

        model.put("host", "req-not_empty");
        model.put("user", "req-not_empty");
        model.put("password", "req-not_empty");
        model.put("google_api_key", "req");
        model.put("bing_api_key", "req");
        model.put("mapping_file", "req");
        model.put("base_file", "req");

        boolean error_flag = false;

        try {
            File conf = new File("config.conf");
            if(!conf.exists()){
//                Files.copy(Paths.get("org/utfpr/alvaras/resources/config.conf"), Paths.get("config.conf"), StandardCopyOption.REPLACE_EXISTING);

                try {
                    File file = new File("config.conf");
                    Writer writer = new FileWriter(file);
                    writer.append("# Configuration file\n\n");
                    writer.append("# Postgre+PostGIS configurations\n\n\n");
                    writer.append("host : jdbc/:postgresql/://127.0.0.1/:5432/alvaras\n\n");
                    writer.append("user : user\n\n");
                    writer.append("password : 1234\n\n\n");
                    writer.append("# GoogleAPI Key\n\n");
                    writer.append("google_api_key : <key>\n\n\n");
                    writer.append("# Bing MapsAPI Key\n\n");
                    writer.append("bing_api_key : <key>\n\n\n");
                    writer.append("# Category Mapping File\n\n");
                    writer.append("mapping_file : \n\n\n");
                    writer.append("# Last file\n\n");
                    writer.append("base_file : Alvaras-Base_de_Dados.CSV");
                    
                    writer.flush();
                    writer.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
            
            config = EasyConfig.getConfigs("config.conf", model, true);

            if (config != null) {
//                jTextField6.setText(config.getProperty("base_file"));
            } else {
                error_flag = true;
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            appendText(ex.getMessage());
            error_flag = true;
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            appendText(ex.getMessage());
        }

        jTextField5.setText("IN DEVELOPMENT");
        
        ((DefaultCaret)jTextArea1.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        setProcessing(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Config");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Gerar Dicionário");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Executar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("<STATUS GOOGLE API>");
        jTextField1.setEnabled(false);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("<STATUS BING API>");
        jTextField2.setEnabled(false);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("<STATUS POSTGRE>");
        jTextField3.setEnabled(false);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("<STATUS CATEGORY>");
        jTextField4.setEnabled(false);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("<STATUS MAP THING>");
        jTextField5.setEnabled(false);

        jTextField6.setText("Selecione arquivo de entrada");

        jButton4.setText("Buscar ...");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Parar execução");
        jButton5.setEnabled(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(43, 43, 43)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextField5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
//        Config c = new Config(this, true, config);
//
//        c.setVisible(true);

        try {
            int ret = JOptionPane.showConfirmDialog(this, "A aplicação será fechada.\nEdite as configurações e reinicie a aplicação.", "Editar configurações", JOptionPane.YES_NO_OPTION);
            
            if(ret == JOptionPane.OK_OPTION){
                String program = (System.getProperty("os.name").toLowerCase().contains("windows") ? "notepad " : "gedit ");
                Process p = Runtime.getRuntime().exec(program + new File("config.conf").getAbsolutePath());
                BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
                stdInput.close();
                
                System.exit(0);
            }
        } catch (Exception k) {
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        File f = new File(jTextField6.getText());
        
        if(!f.isFile()){
            JOptionPane.showMessageDialog(this, "Selecione um arquivo");
            return;
        }
        
        setProcessing(true);
        execution = new Thread(new Runnable() {
            @Override
            public void run() {
                executeChoreography(Choreographer.getDictionaryChain());
                setProcessing(false);
            }
        });
        
        execution.start();
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        File f = new File(jTextField6.getText());
        
        if(!f.isFile()){
            JOptionPane.showMessageDialog(this, "Selecione um arquivo");
            return;
        }
        
        setProcessing(true);
        execution = new Thread(new Runnable() {
            @Override
            public void run() {
                executeChoreography(Choreographer.getExecutionChain(config.getProperty("google_api_key"), config.getProperty("bing_api_key"), config.getProperty("host"), config.getProperty("user"), config.getProperty("password"), thisFrame));
                setProcessing(false);
            }
        });
        
        execution.start();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        
        if(chooser.showDialog(this, "Select") == JFileChooser.APPROVE_OPTION){
            jTextField6.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        if(!jButton5.isEnabled())
            return;
        
        if(execution != null){
            stopExecution = true;
            execution.interrupt();
            setProcessing(false);
        }
    }//GEN-LAST:event_jButton5MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private void setProcessing(boolean isProcessing){
        jButton1.setEnabled(!isProcessing);
        jButton2.setEnabled(!isProcessing);
        jButton3.setEnabled(!isProcessing);
        jButton4.setEnabled(!isProcessing);
        
        jButton5.setEnabled(isProcessing && !stopExecution);
        jButton5.setVisible(isProcessing);
    }
    
    private String convertStatusCode(int statusCode){
        switch(statusCode){
            case ResponsibilityChain.RUNNING:
                return "Running";
            
            case ResponsibilityChain.UNAVAILABLE:
                return "Unavailable";
            
            case ResponsibilityChain.UNKOWN:
                return "Unkown";
            
            case ResponsibilityChain.MISCONFIGURED:
                return "Misconfigures";
            
            case ResponsibilityChain.WEBSERVICE_ERROR:
                return "Error on Web Service Request";
            
            default:
                return "INVALID STATUS";
        }
    }

    private void executeChoreography(ResponsibilityChain<Alvara> chain) {
        BufferedReader reader = null;
        try {
            ResponsibilityChain axLink = chain;
            ResponsibilityChain google = null;
            ResponsibilityChain bing = null;
            ResponsibilityChain postgre = null;
            ResponsibilityChain category = null;
            
            do{
                if(axLink instanceof GeocodingChainLink){
                    google = axLink;
                }else if(axLink instanceof BingGeocoding){
                    bing = axLink;
                }else if(axLink instanceof GISExporter) {
                    postgre = axLink;
                }else if(axLink instanceof ClassifyChainLink){
                    category = axLink;
                }
                
                axLink = axLink.getLink();
            }while(axLink != null);
            
            jTextArea1.setText("");
            appendText("Processamento só pode ser interrompido após a leitura do arquivo.");
            
            stopExecution = true;
            setProcessing(true);
            
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(jTextField6.getText()), "UTF-8"));
            ArrayList<Alvara> alvaras = LerCSV.ler(reader, this);
            
            stopExecution = false;
            setProcessing(true);
            
            appendText(alvaras.size() + " registros encontrados.");
            appendText("Começando processamento:");

            for (Alvara alvara : alvaras) {
                chain.process(alvara);
                
                jTextField1.setText("Google Status: " + convertStatusCode(google.getStatus()));
                jTextField2.setText("Bing Status: " + convertStatusCode(bing.getStatus()));
                jTextField3.setText("Data Bank Status: " + convertStatusCode(postgre.getStatus()));
                jTextField4.setText("Category Definition Status: " + convertStatusCode(category.getStatus()));
                
                if(stopExecution){
                    setTitle("Execução parada");
                    stopExecution = false;
                    return;
                }
            }
            
            setTitle("Processamento finalizado");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            setTitle("ERROR");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public synchronized void appendText(String text) {
        jTextArea1.append(text + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
